CREATE TABLE IF NOT EXISTS `invoices` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `invoice_number` VARCHAR(50) NOT NULL,
  `invoice_date` DATE NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `discount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `paid_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `debt_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `payment_status` ENUM('paid','partial','debt') NOT NULL DEFAULT 'debt',
  `notes` TEXT NULL,
  `status` ENUM('active','cancelled') NOT NULL DEFAULT 'active',
  `pdf_path` VARCHAR(512) NULL,
  `idempotency_key` VARCHAR(64) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_invoice_number` (`company_id`, `invoice_number`),
  KEY `idx_invoices_company_date`   (`company_id`, `invoice_date`),
  KEY `idx_invoices_client`         (`client_id`),
  KEY `idx_idempotency`             (`idempotency_key`),
  CONSTRAINT `fk_invoices_company` FOREIGN KEY (`company_id`)  REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_invoices_client`  FOREIGN KEY (`client_id`)   REFERENCES `clients`   (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_invoices_creator` FOREIGN KEY (`created_by`)  REFERENCES `users`     (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
